In [16]:
import pandas as pd
import ast

In [3]:
df = pd.read_csv("titles.csv")

In [4]:
df.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0,18.216,7.8
3,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0,17.505,7.8
4,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0,95.337,7.7

In [6]:
df.shape

(5806, 15)

In [7]:
print(df)

             id                                title   type  \
0      ts300399  Five Came Back: The Reference Films   SHOW
1       tm84618                          Taxi Driver  MOVIE
2      tm127384      Monty Python and the Holy Grail  MOVIE
3       tm70993                        Life of Brian  MOVIE
4      tm190788                         The Exorcist  MOVIE
...         ...                                  ...    ...
5801  tm1014599                            Fine Wine  MOVIE
5802  tm1108171                       Edis Starlight  MOVIE
5803  tm1045018                                Clash  MOVIE
5804  tm1098060                       Shadow Parties  MOVIE
5805   ts271048   Mighty Little Bheem: Kite Festival   SHOW

                                            description  release_year  \
0     This collection includes 12 World War II-era p...          1945
1     A mentally unstable Vietnam War veteran works ...          1976
2     King Arthur, accompanied by his squire, recrui...          1975
3     Brian Cohen is an average young Jewish man, bu...          1979
4     12-year-old Regan MacNeil begins to adapt an e...          1973
...                                                 ...           ...
5801  A beautiful love story that can happen between...          2021
5802  Rising star Edis's career journey with ups and...          2021
5803  A man from Nigeria returns to his family in Ca...          2021
5804  A family faces destruction in a long-running c...          2021
5805  With winter behind them, Bheem and his townspe...          2021

     age_certification  runtime                             genres  \
0                TV-MA       48                  ['documentation']
1                    R      113                 ['crime', 'drama']
2                   PG       91              ['comedy', 'fantasy']
3                    R       94                         ['comedy']
4                    R      133                         ['horror']
...                ...      ...                                ...
5801               NaN      100               ['romance', 'drama']
5802               NaN       74         ['music', 'documentation']
5803               NaN       88                ['family', 'drama']
5804               NaN      116             ['action', 'thriller']
5805               NaN        0  ['family', 'comedy', 'animation']

     production_countries  seasons     imdb_id  imdb_score  imdb_votes  \
0                  ['US']      1.0         NaN         NaN         NaN
1                  ['US']      NaN   tt0075314         8.3    795222.0
2                  ['GB']      NaN   tt0071853         8.2    530877.0
3                  ['GB']      NaN   tt0079470         8.0    392419.0
4                  ['US']      NaN   tt0070047         8.1    391942.0
...                   ...      ...         ...         ...         ...
5801               ['NG']      NaN  tt13857480         6.9        39.0
5802                   []      NaN         NaN         NaN         NaN
5803         ['NG', 'CA']      NaN  tt14620732         6.5        32.0
5804                   []      NaN  tt10168094         6.2         9.0
5805                   []      1.0  tt13711094         8.8        16.0

      tmdb_popularity  tmdb_score
0               0.600         NaN
1              27.612         8.2
2              18.216         7.8
3              17.505         7.8
4              95.337         7.7
...               ...         ...
5801            0.966         NaN
5802            1.036         8.5
5803            0.709         NaN
5804            2.186         NaN
5805            0.979        10.0

[5806 rows x 15 columns]

In [11]:
df[['title', 'production_countries', 'release_year', 'imdb_score']]

,title,production_countries,release_year,imdb_score
0,Five Came Back: The Reference Films,['US'],1945,NaN
1,Taxi Driver,['US'],1976,8.3
2,Monty Python and the Holy Grail,['GB'],1975,8.2
3,Life of Brian,['GB'],1979,8.0
4,The Exorcist,['US'],1973,8.1
...,...,...,...,...
5801,Fine Wine,['NG'],2021,6.9
5802,Edis Starlight,[],2021,NaN
5803,Clash,"['NG', 'CA']",2021,6.5
5804,Shadow Parties,[],2021,6.2
5805,Mighty Little Bheem: Kite Festival,[],2021,8.8

In [12]:
# Data filtering

movies = df[df["type"] == "MOVIE"]

In [14]:
movies.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0,18.216,7.8
3,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0,17.505,7.8
4,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0,95.337,7.7
6,tm14873,Dirty Harry,MOVIE,When a madman dubbed 'Scorpio' terrorizes San ...,1971,R,102,"['thriller', 'crime', 'action']",['US'],NaN,tt0066999,7.7,153463.0,14.745,7.5

In [18]:
movies = movies.explode('production_countries')

In [19]:
country_count = movies['production_countries'].value_counts()

print(country_count)

production_countries
US    1533
IN     585
GB     260
FR     185
CA     153
      ...
LK       1
GT       1
MZ       1
NA       1
FO       1
Name: count, Length: 104, dtype: int64

In [20]:
top_country = movies['production_countries'].value_counts().idxmax()

print(top_country)

US

In [21]:
print(country_count.head(10))

production_countries
US    1533
IN     585
GB     260
FR     185
CA     153
ES     141
JP     121
DE     107
MX      81
PH      81
Name: count, dtype: int64

In [22]:
# total movies
df['type'].value_counts()

type
MOVIE    3759
SHOW     2047
Name: count, dtype: int64

In [23]:
df.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0,18.216,7.8
3,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0,17.505,7.8
4,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0,95.337,7.7

In [26]:
# String Operations

df['type_num'] = df['type'].map({'MOVIE':1, 'SHOW':0})

In [27]:
df.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,type_num
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN,0
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2,1
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0,18.216,7.8,1
3,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0,17.505,7.8,1
4,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0,95.337,7.7,1

In [28]:
# Grouping

df.groupby('release_year').size()

release_year
1945      1
1953      1
1954      2
1956      1
1958      1
       ...
2018    774
2019    848
2020    805
2021    758
2022    217
Length: 67, dtype: int64

In [30]:
# Country অনুযায়ী movie count

df.groupby('production_countries').size()

production_countries
['AE', 'LB']            3
['AE', 'SA', 'SY']      1
['AE', 'US', 'LB']      1
['AE']                 11
['AF', 'DE', 'PS']      1
                     ...
['ZA', 'GB']            2
['ZA', 'US']            1
['ZA']                 29
['ZW']                  1
[]                    232
Length: 449, dtype: int64

In [31]:
# Genre অনুযায়ী average IMDb score

df.groupby('genres')['imdb_score'].mean()

genres
['action', 'animation', 'comedy', 'crime', 'drama']                                 6.000000
['action', 'animation', 'comedy', 'drama', 'family', 'fantasy', 'scifi']            4.800000
['action', 'animation', 'comedy', 'drama', 'family', 'western', 'documentation']    6.600000
['action', 'animation', 'comedy', 'drama', 'fantasy', 'family']                     6.300000
['action', 'animation', 'comedy', 'drama', 'fantasy', 'romance']                    8.500000
                                                                                      ...
['western', 'thriller', 'action', 'crime', 'drama']                                 7.600000
['western', 'thriller', 'action', 'romance']                                        6.500000
['western', 'thriller', 'horror']                                                   5.500000
['western']                                                                              NaN
[]                                                                                  7.228571
Name: imdb_score, Length: 1626, dtype: float64

In [32]:
# Year অনুযায়ী average runtime

df.groupby('release_year')['runtime'].mean()

release_year
1945     48.000000
1953    105.000000
1954    107.500000
1956    120.000000
1958     77.000000
           ...
2018     73.918605
2019     74.737028
2020     71.915528
2021     73.587071
2022     68.152074
Name: runtime, Length: 67, dtype: float64

In [33]:
# Multiple column grouping

df.groupby(['type', 'release_year']).size()

type   release_year
MOVIE  1953              1
       1954              2
       1956              1
       1958              1
       1959              1
                      ...
SHOW   2018            301
       2019            308
       2020            306
       2021            303
       2022            109
Length: 108, dtype: int64