In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame({
    'Name' : ['Alice', 'Bob', np.nan, 'Daisy', 'Ethan'],
    'Age' : [25, np.nan, 29, 22, np.nan],
    'Salary' : [50000, 60000, np.nan, 58000, 62000]
})

In [3]:
data

    Name   Age   Salary
0  Alice  25.0  50000.0
1    Bob   NaN  60000.0
2    NaN  29.0      NaN
3  Daisy  22.0  58000.0
4  Ethan   NaN  62000.0

In [4]:
# Null value Delete/Dropped

data_dropped = data.dropna()

In [5]:
data_dropped

    Name   Age   Salary
0  Alice  25.0  50000.0
3  Daisy  22.0  58000.0

In [6]:
data

    Name   Age   Salary
0  Alice  25.0  50000.0
1    Bob   NaN  60000.0
2    NaN  29.0      NaN
3  Daisy  22.0  58000.0
4  Ethan   NaN  62000.0

In [7]:
# Data Filled

data_filled = data.fillna({
    'Name' : 'Unknown',
    'Age' : data['Age'].mean(),
    'Salary' : 0
})

In [8]:
data_filled

      Name        Age   Salary
0    Alice  25.000000  50000.0
1      Bob  25.333333  60000.0
2  Unknown  29.000000      0.0
3    Daisy  22.000000  58000.0
4    Ethan  25.333333  62000.0

In [9]:
array_main = np.array([[1,2,3], [4,5,6]])
print(array_main)

[[1 2 3]
 [4 5 6]]

In [10]:
print(array_main.shape)

(2, 3)

In [11]:
reshaped_array = array_main.reshape(3,2)

In [12]:
print(reshaped_array)

[[1 2]
 [3 4]
 [5 6]]

In [14]:
reshaped_array = array_main.reshape(1,6)
print(reshaped_array)

[[1 2 3 4 5 6]]

In [15]:
reshaped_array = array_main.reshape(6,1)
print(reshaped_array)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

In [ ]:
# Vertical Stack (vstack)
# Horizontal Stack (hstack)
# Depth Stack (dstack)

In [17]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [18]:
v_stacked = np.vstack([a, b])
print(v_stacked)

[[1 2]
 [3 4]
 [5 6]]

In [28]:
a = np.array([[1, 2, 5], [3, 4, 9]])
b = np.array([[5, 6], [7, 8]])

In [29]:
h_stacked = np.hstack([a, b])
print(h_stacked)

[[1 2 5 5 6]
 [3 4 9 7 8]]

In [30]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [32]:
d_stacked = np.dstack([a, b])
print(d_stacked)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]

In [33]:
big_array = np.arange(10)
print(big_array)

[0 1 2 3 4 5 6 7 8 9]

In [34]:
split_arrays = np.split(big_array, 2)
print(split_arrays)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [35]:
split_arrays = np.split(big_array, 5)
print(split_arrays)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [36]:
type(split_arrays)

list

In [40]:
sorted_array = np.array([10, 20, 30, 40])
pos =np.searchsorted(sorted_array, 25)
print("Possition : ",pos)

Possition :  2

In [ ]:
# big_array = np.arange(10)
#  print(big_array)

In [41]:
evens = np.where(big_array % 2 == 0)
print("Print Evens number : ",evens)

Print Evens number :  (array([0, 2, 4, 6, 8]),)

In [42]:
sorted_data = data_filled.sort_values(by = 'Salary', ascending=False)
print(sorted_data)

      Name        Age   Salary
4    Ethan  25.333333  62000.0
1      Bob  25.333333  60000.0
3    Daisy  22.000000  58000.0
0    Alice  25.000000  50000.0
2  Unknown  29.000000      0.0

In [43]:
sorted_data = data.sort_values(by = 'Salary', ascending=False)
print(sorted_data)

    Name   Age   Salary
4  Ethan   NaN  62000.0
1    Bob   NaN  60000.0
3  Daisy  22.0  58000.0
0  Alice  25.0  50000.0
2    NaN  29.0      NaN

In [44]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [46]:
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]

In [47]:
arr1 = np.array([[1, 2], [4, 5]])
arr2 = np.array([[4, 5], [8, 9]])

In [48]:
arr = np.concatenate((arr1, arr2))
print(arr)

[[1 2]
 [4 5]
 [4 5]
 [8 9]]

In [49]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]

In [50]:
arr = np.array(['banana', 'apple', 'cherry', 'python'])
print(np.sort(arr))

['apple' 'banana' 'cherry' 'python']