In [1]:
import pandas as pd

data = {
    'Name' : ['Pandy', 'Bamboo', 'Fuzzy'],
    'Age' : [5, 7, 4],
    'Bamboo_Sticks' : [15, 20, 12]
}
df = pd.DataFrame(data)

In [2]:
print(df)

     Name  Age  Bamboo_Sticks
0   Pandy    5             15
1  Bamboo    7             20
2   Fuzzy    4             12

In [3]:
df

     Name  Age  Bamboo_Sticks
0   Pandy    5             15
1  Bamboo    7             20
2   Fuzzy    4             12

In [4]:
df.head()

     Name  Age  Bamboo_Sticks
0   Pandy    5             15
1  Bamboo    7             20
2   Fuzzy    4             12

In [5]:
df[df['Age']<6]

    Name  Age  Bamboo_Sticks
0  Pandy    5             15
2  Fuzzy    4             12

In [6]:
df['Job'] = ['Intern', 'Manager', 'Intern']
print(df)

     Name  Age  Bamboo_Sticks      Job
0   Pandy    5             15   Intern
1  Bamboo    7             20  Manager
2   Fuzzy    4             12   Intern

In [7]:
df.loc[df['Name'] == 'Pandy', 'Age'] = 6

In [8]:
df

     Name  Age  Bamboo_Sticks      Job
0   Pandy    6             15   Intern
1  Bamboo    7             20  Manager
2   Fuzzy    4             12   Intern

In [10]:
df = df.drop('Bamboo_Sticks', axis=1)

In [11]:
df

     Name  Age      Job
0   Pandy    6   Intern
1  Bamboo    7  Manager
2   Fuzzy    4   Intern

In [12]:
df.iloc[2]

Name     Fuzzy
Age          4
Job     Intern
Name: 2, dtype: object

In [13]:
df = pd.DataFrame({
    'Name' : ['Pandy', 'Bamboo', 'Fuzzy', 'Fluffy'],
    'Age' : [5, 7, 4, 6],
    'Bamboo_Stickes' : [15, 20, 12, 18]
}, index = ['a', 'b','c','d'])

In [14]:
df

     Name  Age  Bamboo_Stickes
a   Pandy    5              15
b  Bamboo    7              20
c   Fuzzy    4              12
d  Fluffy    6              18

In [16]:
df.loc['b']

Name              Bamboo
Age                    7
Bamboo_Stickes        20
Name: b, dtype: object

In [17]:
df.loc[['a', 'c'], ['Name', 'Age']]

    Name  Age
a  Pandy    5
c  Fuzzy    4

In [20]:
left = pd.DataFrame({
    'ID' : [1,2,3],
    'Name' : ['Pandy', 'Fuzzy', 'Bamboo']
})

right = pd.DataFrame({
    'ID' : [1,2,4],
    'Hobby' : ['Climbing', 'Sleeping', 'Eating']
})

merged_df = pd.merge(left, right, on='ID', how='right')
print(merged_df)

   ID   Name     Hobby
0   1  Pandy  Climbing
1   2  Fuzzy  Sleeping
2   4    NaN    Eating

In [21]:
concatenated_df = pd.concat([left, right], ignore_index=True)

In [22]:
concatenated_df

   ID    Name     Hobby
0   1   Pandy       NaN
1   2   Fuzzy       NaN
2   3  Bamboo       NaN
3   1     NaN  Climbing
4   2     NaN  Sleeping
5   4     NaN    Eating